python-keyring: fix the dependency on python-hgtools
python-keyring depends on python-hgtools-native, or it fails with:

ERROR: Do not try to fetch `hgtools' for building. Please add its native
recipe to DEPENDS.

Signed-off-by: Jackie Huang <jackie.huang@windriver.com>